---
language: python

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

before_install:
  - deactivate
  - sudo apt-get update -qq

install:
  # Install Python client for docker
  - sudo pip install docker docker-compose

  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create localhost inventory
  - printf localhost > inventory

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/playbook.yml -i inventory --syntax-check

  # Play test
  - ansible-playbook tests/playbook.yml -i inventory --connection=local --sudo

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
