---
- name: config | create docker network
  docker_network:
    name: "{{ item.1.name }}"
  with_subelements:
    - "{{ postgres_databases }}"
    - networks
    - skip_missing: yes

- name: config | run container set
  docker_container:
    name: "{{ item.name }}"
    image: "{{ postgres_image_name }}"
    volumes: "{{ item.volumes | default([]) }}"    
    ports: "{{ item.ports | default([]) }}"
    restart_policy: always
    env: "{{ item.env }}"
    networks: "{{ item.networks|default([]) }}"
  with_items: "{{ postgres_databases }}"
